services:
    postgres:
        image: postgres:17
        container_name: wb_service_postgres
        restart: unless-stopped
        env_file:
            - .env.example
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - development-network

    backend-dev:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: dev
            args:
                NODE_VERSION: 23
        container_name: wb_service_app_dev
        restart: unless-stopped
        depends_on:
            - postgres
        env_file:
            - .env.example
        environment:
            RUNNING_IN_DOCKER: "true"
        command: ["sh", "-c", "npm run migrate:dev && npm run start:dev"]
        ports:
            - "3005:3005"
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        networks:
            - development-network

networks:
    development-network:
        driver: bridge

volumes:
    postgres_data:
    node_modules:
